blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/username/react-native-credentials-manager/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/username/react-native-credentials-manager#readme
    about: Make sure you've read the documentation before filing an issue.
