name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: npm-release
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write

jobs:
  release:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore: release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: '24'

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Setup git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release
        run: yarn release --ci --npm.skipChecks --git.requireBranch=main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
